### ISSUE TITLE
The first and last versions in compatibleRange are not included

### ISSUE THREAD

**Issue by qux7** [ajoberstar/gradle-stutter#37] opened 2024-08-11 22:02 UTC
The first and last versions are not tested against!

1. Create a project with Gradle 8.9 and `id 'org.ajoberstar.stutter' version '1.0.0'`
2. Specify `compatibleRange '6.0.0', '6.5'`:
```
stutter {
  //sparse = false // defaults to true
  matrices {
    java11 {
      javaToolchain {
        languageVersion = JavaLanguageVersion.of(11)
      }
      gradleVersions {
        compatibleRange '6.0.0', '6.5'
      }
    }
  }
```
3. Perform `stutterWriteLocks`
4. See the locks file after `stutterWriteLocks`:
```
$ cat stutter.lockfile 
# DO NOT MODIFY: Generated by Stutter plugin.
java11=6.0.1,6.4.1
```

**Expected:** both '6.0.0' and '6.5'` are included

**Actual:**  neither '6.0.0' nor '6.5'` are included

The same misbehavior happens with `sparse = false`:
```
$ cat stutter.lockfile 
# DO NOT MODIFY: Generated by Stutter plugin.
java11=6.0.1,6.1.1,6.2.2,6.3,6.4.1
```

(My guess is that this is somehow related to using the last available patch.)

**Comment by ajoberstar** [comment] 2024-08-12 20:17
This is caused by two (intentional) parts of the implementation:

1. `6.5` is excluded because the `compatibleRange()` takes an _inclusive_ start version and an _exclusive_ end version. So by definition, `6.5` would not be included in this range. The intent of this method is to say something like `compatibleRange('7.3', '8.0')` where you know that `8.0` is not compatible with your plugin.
2. `6.0` is replaced with `6.0.1` because we intentionally only include the latest patch version of any given minor. See the code [here](https://github.com/ajoberstar/gradle-stutter/blob/422151b5e65b86900a2f33fc97308b8938fc5ee7/src/main/java/org/ajoberstar/gradle/stutter/StutterGradleVersions.java#L72-L76). This motivated by #17 where the requester highlighted that including _every_ version in a range would often result in far more tests than anyone practically wants to run. It's a performance optimization relying on the presumption that a Gradle patch release should be functionally equivalent to the `x.y.0` base release outside of bugs Gradle acknowledged and fixed.

**Comment by ajoberstar** [comment] 2024-11-23 23:25
Closing since this is intentional behavior.

**Closed as not planned by ajoberstar** 2024-11-23 23:25 UTC
